@echo off
echo Starting TASKAPP backend server...
cd /d "E:\Hackathon 2\Phase-II\Full-Stack-Web-Application\backend"

echo Waiting for database initialization...
echo This may take 1-2 minutes on first startup...

python -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --timeout-keep-alive 60